apiVersion: v2
appVersion: v0.0.1
description: Automated tcp port mapping for the nginx ingress controller
home: https://github.com/DoodleScheduling/k8stcpmap-controller
maintainers:
- name: devops
  email: devops@doodle.com
keywords:
- kubernetes-controller
- nginx-ingress
name: k8stcpmap-controller
sources:
- https://github.com/DoodleScheduling/k8stcpmap-controller
version: 0.1.2
